import type { Property } from "./types";
export const properties: Property[] = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    name: "Alam Villa Langkawi",
    slug: "alam-villa-langkawi",
    description:
      "A serene timber villa wrapped in tropical gardens, made for unhurried family days near Pantai Cenang.",
    address: "18 Jalan Pantai Tengah",
    city: "Langkawi",
    state: "Kedah",
    maxGuests: 8,
    bedrooms: 3,
    bathrooms: 3,
    basePriceSen: 62000,
    cleaningFeeSen: 9000,
    securityDepositSen: 30000,
    checkInTime: "15:00",
    checkOutTime: "11:00",
    houseRules: "No smoking indoors. Quiet hours begin at 10:00 PM.",
    cancellationPolicy: "Free cancellation until 3 days before check-in.",
    images: [
      {
        url: "/assets/alam-villa-hero.png",
        alt: "Alam Villa tropical exterior",
      },
      {
        url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1000&q=85",
        alt: "Warm villa living room",
      },
    ],
    rooms: [],
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    name: "Damai Hillside Home",
    slug: "damai-hillside-home",
    description:
      "A breezy hillside retreat with generous gathering spaces and calm valley views outside Bentong.",
    address: "27 Jalan Bukit Damai",
    city: "Bentong",
    state: "Pahang",
    maxGuests: 10,
    bedrooms: 4,
    bathrooms: 3,
    basePriceSen: 68000,
    cleaningFeeSen: 10000,
    securityDepositSen: 35000,
    checkInTime: "15:00",
    checkOutTime: "11:00",
    houseRules: "No parties without prior approval.",
    cancellationPolicy: "Free cancellation until 3 days before check-in.",
    images: [
      {
        url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1600&q=85",
        alt: "Damai Hillside pool villa",
      },
    ],
    rooms: [],
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    name: "Rimba Retreat Janda Baik",
    slug: "rimba-retreat-janda-baik",
    description:
      "A cool forest hideaway beside the river, designed for quiet weekends and small celebrations.",
    address: "Lot 12 Kampung Sum-Sum",
    city: "Janda Baik",
    state: "Pahang",
    maxGuests: 6,
    bedrooms: 2,
    bathrooms: 2,
    basePriceSen: 52000,
    cleaningFeeSen: 8000,
    securityDepositSen: 25000,
    checkInTime: "15:00",
    checkOutTime: "11:00",
    houseRules: "Respect the river and surrounding village.",
    cancellationPolicy: "Free cancellation until 3 days before check-in.",
    images: [
      {
        url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1600&q=85",
        alt: "Rimba Retreat forest home",
      },
    ],
    rooms: [],
  },
];
