export type Image = { id?: string; url: string; alt: string };
export type Room = {
  id: string;
  name: string;
  roomType: string;
  capacity: number;
  bedConfig: string;
  priceSen: number;
  images: Image[];
};
export type Property = {
  id: string;
  name: string;
  slug: string;
  description: string;
  address: string;
  city: string;
  state: string;
  maxGuests: number;
  bedrooms: number;
  bathrooms: number;
  basePriceSen: number;
  cleaningFeeSen: number;
  securityDepositSen: number;
  checkInTime: string;
  checkOutTime: string;
  houseRules: string;
  cancellationPolicy: string;
  images: Image[];
  rooms: Room[];
  amenities?: Array<{ amenity: { id: string; name: string } }>;
  entirePropertyAvailable?: boolean;
  availableRooms?: Room[];
};
export type Booking = {
  id: string;
  reference: string;
  status: string;
  paymentStatus?: string;
  checkIn: string;
  checkOut: string;
  guestCount: number;
  adultCount: number;
  childCount: number;
  totalSen: number;
  expiresAt?: string | null;
  property: Property;
  items: Array<{ room?: Room }>;
  payments: Array<{ verificationStatus: string }>;
};
export type ReservationResult = {
  booking: Booking & {
    userId?: string | null;
    subtotalSen: number;
    cleaningFeeSen: number;
    extraGuestFeeSen: number;
  };
  whatsappUrl: string;
};
export type ApiResponse<T> = { success: boolean; data: T; message: string };
