-- No customer records, phone numbers, policies or capacities are fabricated.
-- Sample rates are installed by the migration, explicitly marked demo_rates=true.
-- Complete property configuration using /admin before enabling live bookings.
