"use client";
import "./booking.css";
import { FormEvent, Suspense, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { saveBooking, whatsappUrl, type LocalBooking } from "@/lib/demo-bookings";
import { units } from "@/data/units";

const money=(value:number)=>`RM ${value.toLocaleString("en-MY",{minimumFractionDigits:2})}`;
function BookingForm(){
  const query=useSearchParams();
  const [unitName,setUnitName]=useState(units[0].name),[payment,setPayment]=useState("deposit_20");
  const checkIn=query.get("checkin")||"",checkOut=query.get("checkout")||"";
  const pricing=useMemo(()=>{const unit=units.find(item=>item.name===unitName)||units[0];const start=checkIn?new Date(`${checkIn}T00:00:00`):null,end=checkOut?new Date(`${checkOut}T00:00:00`):null,nights=start&&end?Math.max(1,Math.round((end.getTime()-start.getTime())/86_400_000)):1,total=unit.basePrice*nights,rate=payment==="deposit_20"?.2:payment==="deposit_50"?.5:1;return {unit,nights,total,rate,due:total*rate}},[unitName,payment,checkIn,checkOut]);
  const [booking,setBooking]=useState<(LocalBooking&{total:number;amountDue:number})|null>(null);
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),id=`SH-${Date.now().toString(36).toUpperCase()}`,paymentLabel=payment==="full"?"full payment":`${Math.round(pricing.rate*100)}% deposit`,record={id,name:String(form.get("name")),phone:String(form.get("phone")),email:String(form.get("email")),unit:unitName,checkIn:String(form.get("checkIn")),checkOut:String(form.get("checkOut")),guests:Number(form.get("guests")),payment:paymentLabel as "deposit"|"full",status:"awaiting_payment" as const,createdAt:new Date().toISOString(),total:pricing.total,amountDue:pricing.due};saveBooking(record);setBooking(record)}
  if(booking){const message=`SukaHomestay booking request\nReference: ${booking.id}\nName: ${booking.name}\nStay: ${booking.unit}\nDates: ${booking.checkIn} to ${booking.checkOut}\nGuests: ${booking.guests}\nTotal stay: ${money(booking.total)}\nAmount due now: ${money(booking.amountDue)} (${booking.payment})`;const receipt=`Payment receipt for ${booking.id}\nAmount paid: ${money(booking.amountDue)}\nPlease attach your bank receipt to this WhatsApp message.`;return <section className="section"><div className="shell"><span className="eyebrow">Booking request received</span><h1 className="title">Your reference is {booking.id}</h1><div className="table"><p><strong>Amount to pay now: {money(booking.amountDue)}</strong></p><p>Send your booking details to the host. After bank transfer, attach the receipt in the same WhatsApp chat.</p><div className="actions"><a className="button" href={whatsappUrl(message)}>Send booking to WhatsApp</a><a className="button secondary" href={whatsappUrl(receipt)}>Send payment receipt</a></div></div></div></section>}
  return <section className="section"><div className="shell"><span className="eyebrow">Reserve your stay</span><h1 className="title">Complete your booking details</h1><p className="lead">Your dates are selected from the availability calendar. Choose the payment amount before sending the booking to WhatsApp.</p><form className="form" onSubmit={submit}><input name="name" required placeholder="Full name"/><input name="phone" required placeholder="WhatsApp number"/><input name="email" type="email" required placeholder="Email address"/><select name="unit" value={unitName} onChange={e=>setUnitName(e.target.value)}>{units.map(unit=><option key={unit.id} value={unit.name}>{unit.name} — from RM {unit.basePrice}/night</option>)}</select><input className="muted-field" name="checkIn" type="date" required readOnly value={checkIn}/><input className="muted-field" name="checkOut" type="date" required readOnly value={checkOut}/><input name="guests" type="number" min="1" required defaultValue="2"/><select name="payment" value={payment} onChange={e=>setPayment(e.target.value)}><option value="deposit_20">Pay 20% deposit</option><option value="deposit_50">Pay 50% deposit</option><option value="full">Pay full amount</option></select><div className="price-summary"><span>{pricing.nights} night{pricing.nights!==1?"s":""} × {money(pricing.unit.basePrice)}</span><strong>Total stay: {money(pricing.total)}</strong><b>Pay admin now: {money(pricing.due)} {pricing.rate<1?`(${Math.round(pricing.rate*100)}% deposit)`:"(full payment)"}</b></div><button className="button">Create booking & continue to WhatsApp</button></form></div></section>}
export default function Booking(){return <Suspense fallback={<section className="section"><div className="shell">Loading booking form…</div></section>}><BookingForm/></Suspense>}
