import { Router } from "express";
import * as controller from "../controllers/admin.controller.js";
import { requireAuth, requireRole } from "../middleware/auth.js";
import { asyncHandler } from "../utils/async-handler.js";
export const adminRouter = Router();
adminRouter.use(requireAuth, requireRole("ADMIN"));
adminRouter.get("/dashboard", asyncHandler(controller.dashboard));
adminRouter.get("/bookings", asyncHandler(controller.bookings));
adminRouter.get("/bookings/:id", asyncHandler(controller.booking));
adminRouter.get("/bookings/:id/contact", asyncHandler(controller.contactCustomer));
adminRouter.post("/bookings/:id/approve", asyncHandler(controller.approveBooking));
adminRouter.post("/bookings/:id/reject", asyncHandler(controller.rejectBooking));
adminRouter.post("/bookings/:id/extend-expiry", asyncHandler(controller.extendExpiry));
adminRouter.patch("/bookings/:id/dates", asyncHandler(controller.editDates));
adminRouter.post("/bookings/:id/payment-submitted", asyncHandler(controller.submitPayment));
adminRouter.post("/bookings/:id/verify-payment", asyncHandler(controller.verifyPayment));
adminRouter.post("/bookings/:id/reject-payment", asyncHandler(controller.rejectPayment));
adminRouter.post("/bookings/:id/cancel", asyncHandler(controller.cancelBooking));
adminRouter.post("/bookings/:id/stay-status", asyncHandler(controller.updateStayStatus));
adminRouter.get("/settings", asyncHandler(controller.settings));
adminRouter.put("/settings", asyncHandler(controller.updateSettings));
adminRouter.get("/calendar", asyncHandler(controller.calendar));
adminRouter.get("/payments/:id/receipt-url", asyncHandler(controller.receiptUrl));
adminRouter.post("/properties", asyncHandler(controller.createProperty));
adminRouter.put("/properties/:id", asyncHandler(controller.updateProperty));
adminRouter.post("/properties/:propertyId/rooms", asyncHandler(controller.createRoom));
adminRouter.put("/rooms/:id", asyncHandler(controller.updateRoom));
adminRouter.put("/rate-plans/:id", asyncHandler(controller.updateRatePlan));
adminRouter.post("/calendar/blocks", asyncHandler(controller.blockDates));
