export type UserRole = "CUSTOMER" | "ADMIN";
export type BookingStatus = "PENDING_APPROVAL" | "AWAITING_PAYMENT" | "PAYMENT_SUBMITTED" | "CONFIRMED" | "CHECKED_IN" | "COMPLETED" | "REJECTED" | "CANCELLED" | "EXPIRED";
export type InventoryType = "ENTIRE_PROPERTY" | "ROOM";
export type NotificationType = "BOOKING_CREATED" | "PAYMENT_RECEIVED" | "BOOKING_CONFIRMED" | "PAYMENT_FAILED" | "BOOKING_CANCELLED" | "CHECKIN_REMINDER" | "CHECKOUT_REMINDER" | "REFUND_PROCESSED";
