"use client";
import "./admin.css";
import "./drawer.css";
import "./mobile-overrides.css";
import Link from "next/link";
import { LogOut, Menu, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/browser";
const links=["Overview","Bookings","Calendar","Accommodations","Pricing","Payments","Customers","Gallery","Amenities","Blocked dates","Promotions","Reviews","Settings"];
export default function AdminLayout({children}:{children:React.ReactNode}){const router=useRouter(),[menuOpen,setMenuOpen]=useState(false);useEffect(()=>{const close=(event:KeyboardEvent)=>event.key==="Escape"&&setMenuOpen(false);window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[]);async function signOut(){await createClient().auth.signOut();router.push("/");router.refresh()}const nav=<nav aria-label="Admin navigation">{links.map(x=><Link onClick={()=>setMenuOpen(false)} href={x==="Overview"?"/admin":`/admin/${x.toLowerCase().replace(" ","-")}`} key={x}>{x}</Link>)}</nav>;return <div className="dash admin-shell"><aside className="side admin-side"><div className="admin-brand"><strong>Admin console</strong><span>SukaHomestay</span></div>{nav}<button className="admin-signout" onClick={signOut}><LogOut size={17}/> Sign out</button></aside><main className="main admin-main"><div className="admin-mobile-bar"><strong>Admin console</strong><div><button className="admin-signout" onClick={signOut}><LogOut size={17}/> Sign out</button><button className="admin-menu-button" aria-label="Open admin menu" aria-expanded={menuOpen} onClick={()=>setMenuOpen(true)}><Menu size={21}/></button></div></div>{children}</main>{menuOpen&&<button className="admin-backdrop" aria-label="Close menu" onClick={()=>setMenuOpen(false)}/>}<aside className={`admin-drawer ${menuOpen?"open":""}`} aria-hidden={!menuOpen}><div className="drawer-head"><strong>Admin navigation</strong><button aria-label="Close menu" onClick={()=>setMenuOpen(false)}><X size={21}/></button></div>{nav}<button className="admin-signout" onClick={signOut}><LogOut size={17}/> Sign out</button></aside></div>}
